#pragma once

// Generated by scripts/extract_spu2_reverb_presets.py -- do not hand-edit.
//
// The ten reverb presets out of the game's own IOP sound driver,
// RSPU2DRV.IRX, which is where a music record's `+4` reverb type is
// resolved. Field order and units are the driver's, read off its register
// writer at 0xF6F0:
//
//   * `sizeUnits` is the delay buffer, in eight-byte units. The driver
//     shifts it left by three for bytes and parks the buffer at the top of
//     sound RAM.
//   * every `*Size`, `*Src` and `*Dst` is an offset into that buffer, in
//     eight-byte units as well; the driver multiplies by four on the way to
//     the hardware register, because SPU2 addresses 16-bit words. Four
//     samples per unit, either way you count it.
//   * every `*Vol` and `inCoef*` is a signed Q15 coefficient.

#include <array>
#include <cstddef>
#include <cstdint>

namespace orphen::ported::sound
{

  struct Spu2ReverbPreset
  {
    std::uint32_t sizeUnits;
    std::uint16_t apf1Size;
    std::uint16_t apf2Size;
    std::int16_t iirVol;
    std::int16_t comb1Vol;
    std::int16_t comb2Vol;
    std::int16_t comb3Vol;
    std::int16_t comb4Vol;
    std::int16_t wallVol;
    std::int16_t apf1Vol;
    std::int16_t apf2Vol;
    std::uint16_t sameLDst;
    std::uint16_t sameRDst;
    std::uint16_t comb1LSrc;
    std::uint16_t comb1RSrc;
    std::uint16_t comb2LSrc;
    std::uint16_t comb2RSrc;
    std::uint16_t sameLSrc;
    std::uint16_t sameRSrc;
    std::uint16_t diffLDst;
    std::uint16_t diffRDst;
    std::uint16_t comb3LSrc;
    std::uint16_t comb3RSrc;
    std::uint16_t comb4LSrc;
    std::uint16_t comb4RSrc;
    std::uint16_t diffLSrc;
    std::uint16_t diffRSrc;
    std::uint16_t apf1LDst;
    std::uint16_t apf1RDst;
    std::uint16_t apf2LDst;
    std::uint16_t apf2RDst;
    std::int16_t inCoefL;
    std::int16_t inCoefR;
  };

  inline constexpr std::size_t kSpu2ReverbPresetCount = 10;

  inline constexpr std::array<Spu2ReverbPreset, kSpu2ReverbPresetCount>
      kSpu2ReverbPresets{{
      // mode 0: Off
      {
          0x0002,
          0x0000, // APF1_SIZE
          0x0000, // APF2_SIZE
          0, // IIR_VOL
          0, // COMB1_VOL
          0, // COMB2_VOL
          0, // COMB3_VOL
          0, // COMB4_VOL
          0, // WALL_VOL
          0, // APF1_VOL
          0, // APF2_VOL
          0x0001, // SAME_L_DST
          0x0001, // SAME_R_DST
          0x0000, // COMB1_L_SRC
          0x0000, // COMB1_R_SRC
          0x0000, // COMB2_L_SRC
          0x0000, // COMB2_R_SRC
          0x0000, // SAME_L_SRC
          0x0000, // SAME_R_SRC
          0x0001, // DIFF_L_DST
          0x0001, // DIFF_R_DST
          0x0000, // COMB3_L_SRC
          0x0000, // COMB3_R_SRC
          0x0000, // COMB4_L_SRC
          0x0000, // COMB4_R_SRC
          0x0000, // DIFF_L_SRC
          0x0000, // DIFF_R_SRC
          0x0000, // APF1_L_DST
          0x0000, // APF1_R_DST
          0x0000, // APF2_L_DST
          0x0000, // APF2_R_DST
          0, // IN_COEF_L
          0, // IN_COEF_R
      },
      // mode 1: Room
      {
          0x04D8,
          0x007D, // APF1_SIZE
          0x005B, // APF2_SIZE
          28032, // IIR_VOL
          21688, // COMB1_VOL
          -16688, // COMB2_VOL
          0, // COMB3_VOL
          0, // COMB4_VOL
          -17792, // WALL_VOL
          22528, // APF1_VOL
          21248, // APF2_VOL
          0x04D6, // SAME_L_DST
          0x0333, // SAME_R_DST
          0x03F0, // COMB1_L_SRC
          0x0227, // COMB1_R_SRC
          0x0374, // COMB2_L_SRC
          0x01EF, // COMB2_R_SRC
          0x0336, // SAME_L_SRC
          0x01B7, // SAME_R_SRC
          0x0335, // DIFF_L_DST
          0x01B6, // DIFF_R_DST
          0x0334, // COMB3_L_SRC
          0x01B5, // COMB3_R_SRC
          0x0334, // COMB4_L_SRC
          0x01B5, // COMB4_R_SRC
          0x0334, // DIFF_L_SRC
          0x01B5, // DIFF_R_SRC
          0x01B4, // APF1_L_DST
          0x0136, // APF1_R_DST
          0x00B8, // APF2_L_DST
          0x005C, // APF2_R_DST
          -32768, // IN_COEF_L
          -32768, // IN_COEF_R
      },
      // mode 2: StudioA
      {
          0x03E8,
          0x0033, // APF1_SIZE
          0x0025, // APF2_SIZE
          28912, // IIR_VOL
          20392, // COMB1_VOL
          -17184, // COMB2_VOL
          17424, // COMB3_VOL
          -16144, // COMB4_VOL
          -25600, // WALL_VOL
          21120, // APF1_VOL
          20160, // APF2_VOL
          0x03E4, // SAME_L_DST
          0x031B, // SAME_R_DST
          0x03A4, // COMB1_L_SRC
          0x02AF, // COMB1_R_SRC
          0x0372, // COMB2_L_SRC
          0x0266, // COMB2_R_SRC
          0x031C, // SAME_L_SRC
          0x025D, // SAME_R_SRC
          0x025C, // DIFF_L_DST
          0x018E, // DIFF_R_DST
          0x022F, // COMB3_L_SRC
          0x0135, // COMB3_R_SRC
          0x01D2, // COMB4_L_SRC
          0x00B7, // COMB4_R_SRC
          0x018F, // DIFF_L_SRC
          0x00B5, // DIFF_R_SRC
          0x00B4, // APF1_L_DST
          0x0080, // APF1_R_DST
          0x004C, // APF2_L_DST
          0x0026, // APF2_R_DST
          -32768, // IN_COEF_L
          -32768, // IN_COEF_R
      },
      // mode 3: StudioB
      {
          0x0908,
          0x00B1, // APF1_SIZE
          0x007F, // APF2_SIZE
          28912, // IIR_VOL
          20392, // COMB1_VOL
          -17184, // COMB2_VOL
          17680, // COMB3_VOL
          -16656, // COMB4_VOL
          -19264, // WALL_VOL
          21120, // APF1_VOL
          20160, // APF2_VOL
          0x0904, // SAME_L_DST
          0x076B, // SAME_R_DST
          0x0824, // COMB1_L_SRC
          0x065F, // COMB1_R_SRC
          0x07A2, // COMB2_L_SRC
          0x0616, // COMB2_R_SRC
          0x076C, // SAME_L_SRC
          0x05ED, // SAME_R_SRC
          0x05EC, // DIFF_L_DST
          0x042E, // DIFF_R_DST
          0x050F, // COMB3_L_SRC
          0x0305, // COMB3_R_SRC
          0x0462, // COMB4_L_SRC
          0x02B7, // COMB4_R_SRC
          0x042F, // DIFF_L_SRC
          0x0265, // DIFF_R_SRC
          0x0264, // APF1_L_DST
          0x01B2, // APF1_R_DST
          0x0100, // APF2_L_DST
          0x0080, // APF2_R_DST
          -32768, // IN_COEF_L
          -32768, // IN_COEF_R
      },
      // mode 4: StudioC
      {
          0x0DFC,
          0x00E3, // APF1_SIZE
          0x00A9, // APF2_SIZE
          28512, // IIR_VOL
          20392, // COMB1_VOL
          -17184, // COMB2_VOL
          17680, // COMB3_VOL
          -16656, // COMB4_VOL
          -22912, // WALL_VOL
          22144, // APF1_VOL
          21184, // APF2_VOL
          0x0DFB, // SAME_L_DST
          0x0B58, // SAME_R_DST
          0x0D09, // COMB1_L_SRC
          0x0A3C, // COMB1_R_SRC
          0x0BD9, // COMB2_L_SRC
          0x0973, // COMB2_R_SRC
          0x0B59, // SAME_L_SRC
          0x08DA, // SAME_R_SRC
          0x08D9, // DIFF_L_DST
          0x05E9, // DIFF_R_DST
          0x07EC, // COMB3_L_SRC
          0x04B0, // COMB3_R_SRC
          0x06EF, // COMB4_L_SRC
          0x03D2, // COMB4_R_SRC
          0x05EA, // DIFF_L_SRC
          0x031D, // DIFF_R_SRC
          0x031C, // APF1_L_DST
          0x0238, // APF1_R_DST
          0x0154, // APF2_L_DST
          0x00AA, // APF2_R_DST
          -32768, // IN_COEF_L
          -32768, // IN_COEF_R
      },
      // mode 5: Hall
      {
          0x15BC,
          0x01A5, // APF1_SIZE
          0x0139, // APF2_SIZE
          24576, // IIR_VOL
          20480, // COMB1_VOL
          19456, // COMB2_VOL
          -18432, // COMB3_VOL
          -17408, // COMB4_VOL
          -16384, // WALL_VOL
          24576, // APF1_VOL
          23552, // APF2_VOL
          0x15BA, // SAME_L_DST
          0x11BB, // SAME_R_DST
          0x14C2, // COMB1_L_SRC
          0x10BD, // COMB1_R_SRC
          0x11BC, // COMB2_L_SRC
          0x0DC1, // COMB2_R_SRC
          0x11C0, // SAME_L_SRC
          0x0DC3, // SAME_R_SRC
          0x0DC0, // DIFF_L_DST
          0x09C1, // DIFF_R_DST
          0x0BC4, // COMB3_L_SRC
          0x07C1, // COMB3_R_SRC
          0x0A00, // COMB4_L_SRC
          0x06CD, // COMB4_R_SRC
          0x09C2, // DIFF_L_SRC
          0x05C1, // DIFF_R_SRC
          0x05C0, // APF1_L_DST
          0x041A, // APF1_R_DST
          0x0274, // APF2_L_DST
          0x013A, // APF2_R_DST
          -32768, // IN_COEF_L
          -32768, // IN_COEF_R
      },
      // mode 6: SpaceEcho
      {
          0x1ED8,
          0x033D, // APF1_SIZE
          0x0231, // APF2_SIZE
          32256, // IIR_VOL
          20480, // COMB1_VOL
          -19456, // COMB2_VOL
          -20480, // COMB3_VOL
          19456, // COMB4_VOL
          -20480, // WALL_VOL
          24576, // APF1_VOL
          21504, // APF2_VOL
          0x1ED6, // SAME_L_DST
          0x1A31, // SAME_R_DST
          0x1D14, // COMB1_L_SRC
          0x183B, // COMB1_R_SRC
          0x1BC2, // COMB2_L_SRC
          0x16B2, // COMB2_R_SRC
          0x1A32, // SAME_L_SRC
          0x15EF, // SAME_R_SRC
          0x15EE, // DIFF_L_DST
          0x1055, // DIFF_R_DST
          0x1334, // COMB3_L_SRC
          0x0F2D, // COMB3_R_SRC
          0x11F6, // COMB4_L_SRC
          0x0C5D, // COMB4_R_SRC
          0x1056, // DIFF_L_SRC
          0x0AE1, // DIFF_R_SRC
          0x0AE0, // APF1_L_DST
          0x07A2, // APF1_R_DST
          0x0464, // APF2_L_DST
          0x0232, // APF2_R_DST
          -32768, // IN_COEF_L
          -32768, // IN_COEF_R
      },
      // mode 7: Echo
      {
          0x3008,
          0x0003, // APF1_SIZE
          0x0003, // APF2_SIZE
          32767, // IIR_VOL
          32767, // COMB1_VOL
          0, // COMB2_VOL
          0, // COMB3_VOL
          0, // COMB4_VOL
          -32512, // WALL_VOL
          0, // APF1_VOL
          0, // APF2_VOL
          0x1FFD, // SAME_L_DST
          0x0FFD, // SAME_R_DST
          0x1009, // COMB1_L_SRC
          0x0009, // COMB1_R_SRC
          0x0000, // COMB2_L_SRC
          0x0000, // COMB2_R_SRC
          0x1009, // SAME_L_SRC
          0x0009, // SAME_R_SRC
          0x1FFF, // DIFF_L_DST
          0x1FFF, // DIFF_R_DST
          0x1FFE, // COMB3_L_SRC
          0x1FFE, // COMB3_R_SRC
          0x1FFE, // COMB4_L_SRC
          0x1FFE, // COMB4_R_SRC
          0x1FFE, // DIFF_L_SRC
          0x1FFE, // DIFF_R_SRC
          0x1008, // APF1_L_DST
          0x1004, // APF1_R_DST
          0x0008, // APF2_L_DST
          0x0004, // APF2_R_DST
          -32768, // IN_COEF_L
          -32768, // IN_COEF_R
      },
      // mode 8: Delay
      {
          0x3008,
          0x0003, // APF1_SIZE
          0x0003, // APF2_SIZE
          32767, // IIR_VOL
          32767, // COMB1_VOL
          0, // COMB2_VOL
          0, // COMB3_VOL
          0, // COMB4_VOL
          0, // WALL_VOL
          0, // APF1_VOL
          0, // APF2_VOL
          0x1FFD, // SAME_L_DST
          0x0FFD, // SAME_R_DST
          0x1009, // COMB1_L_SRC
          0x0009, // COMB1_R_SRC
          0x0000, // COMB2_L_SRC
          0x0000, // COMB2_R_SRC
          0x1009, // SAME_L_SRC
          0x0009, // SAME_R_SRC
          0x1FFF, // DIFF_L_DST
          0x1FFF, // DIFF_R_DST
          0x1FFE, // COMB3_L_SRC
          0x1FFE, // COMB3_R_SRC
          0x1FFE, // COMB4_L_SRC
          0x1FFE, // COMB4_R_SRC
          0x1FFE, // DIFF_L_SRC
          0x1FFE, // DIFF_R_SRC
          0x1008, // APF1_L_DST
          0x1004, // APF1_R_DST
          0x0008, // APF2_L_DST
          0x0004, // APF2_R_DST
          -32768, // IN_COEF_L
          -32768, // IN_COEF_R
      },
      // mode 9: Pipe
      {
          0x0780,
          0x0017, // APF1_SIZE
          0x0013, // APF2_SIZE
          28912, // IIR_VOL
          20392, // COMB1_VOL
          -17184, // COMB2_VOL
          17680, // COMB3_VOL
          -16656, // COMB4_VOL
          -31488, // WALL_VOL
          24448, // APF1_VOL
          21696, // APF2_VOL
          0x0371, // SAME_L_DST
          0x02AF, // SAME_R_DST
          0x02E5, // COMB1_L_SRC
          0x01DF, // COMB1_R_SRC
          0x02B0, // COMB2_L_SRC
          0x01D7, // COMB2_R_SRC
          0x0358, // SAME_L_SRC
          0x026A, // SAME_R_SRC
          0x01D6, // DIFF_L_DST
          0x011E, // DIFF_R_DST
          0x012D, // COMB3_L_SRC
          0x00B1, // COMB3_R_SRC
          0x011F, // COMB4_L_SRC
          0x0059, // COMB4_R_SRC
          0x01A0, // DIFF_L_SRC
          0x00E3, // DIFF_R_SRC
          0x0058, // APF1_L_DST
          0x0040, // APF1_R_DST
          0x0028, // APF2_L_DST
          0x0014, // APF2_R_DST
          -32768, // IN_COEF_L
          -32768, // IN_COEF_R
      },
  }};

} // namespace orphen::ported::sound
