#!/usr/bin/env python3
"""Extract the SPU2 reverb preset bank out of RSPU2DRV.IRX.

The EE never holds these numbers. A music record's `+4` is a reverb *type*,
which FUN_00205938 forwards to the IOP as command 0x7314; the table that turns a
type into hardware coefficients lives in the game's own sound driver,
`cdrom0:\\RSPU2DRV.IRX`, which is on the disc but not in the flattened disc root.

Two tables, both in the module's `.data` (vaddr 0x160E0, file offset 0x16180):

  0x16390  ten u32 buffer sizes, in eight-byte units
  0x163C0  ten 0x44-byte entries: { u32 fieldMask; u16 params[32] }

`fieldMask` is zero in every shipped entry, which the driver reads as "write
every field". The parameter order was taken from the driver's own writer at
0xF6F0, which walks the entry front to back against ascending SPU2 register
indices -- see REGISTERS below.

Usage:
    python scripts/extract_spu2_reverb_presets.py RSPU2DRV.IRX --header out.h
    python scripts/extract_spu2_reverb_presets.py game.iso --header out.h
"""

import argparse
import struct
import sys

# .data section: file offset 0x16180 holds vaddr 0x160E0.
DATA_FILE_TO_VADDR = 0x160E0 - 0x16180

SIZE_TABLE_VADDR = 0x16390
PRESET_TABLE_VADDR = 0x163C0
PRESET_STRIDE = 0x44
PRESET_COUNT = 10

# The order the driver's register writer at 0xF6F0 walks them in. Register
# offsets are SPU2 core-relative; that helper takes them pre-halved, so 0x2E4
# shows up there as 0x172.
REGISTERS = [
    ("APF1_SIZE", 0x2E4, "addr"),
    ("APF2_SIZE", 0x2E8, "addr"),
    ("IIR_VOL", 0x774, "coef"),
    ("COMB1_VOL", 0x776, "coef"),
    ("COMB2_VOL", 0x778, "coef"),
    ("COMB3_VOL", 0x77A, "coef"),
    ("COMB4_VOL", 0x77C, "coef"),
    ("WALL_VOL", 0x77E, "coef"),
    ("APF1_VOL", 0x780, "coef"),
    ("APF2_VOL", 0x782, "coef"),
    ("SAME_L_DST", 0x2EC, "addr"),
    ("SAME_R_DST", 0x2F0, "addr"),
    ("COMB1_L_SRC", 0x2F4, "addr"),
    ("COMB1_R_SRC", 0x2F8, "addr"),
    ("COMB2_L_SRC", 0x2FC, "addr"),
    ("COMB2_R_SRC", 0x300, "addr"),
    ("SAME_L_SRC", 0x304, "addr"),
    ("SAME_R_SRC", 0x308, "addr"),
    ("DIFF_L_DST", 0x30C, "addr"),
    ("DIFF_R_DST", 0x310, "addr"),
    ("COMB3_L_SRC", 0x314, "addr"),
    ("COMB3_R_SRC", 0x318, "addr"),
    ("COMB4_L_SRC", 0x31C, "addr"),
    ("COMB4_R_SRC", 0x320, "addr"),
    ("DIFF_L_SRC", 0x324, "addr"),
    ("DIFF_R_SRC", 0x328, "addr"),
    ("APF1_L_DST", 0x32C, "addr"),
    ("APF1_R_DST", 0x330, "addr"),
    ("APF2_L_DST", 0x334, "addr"),
    ("APF2_R_DST", 0x338, "addr"),
    ("IN_COEF_L", 0x784, "coef"),
    ("IN_COEF_R", 0x786, "coef"),
]

# The driver's mode numbering, 0..9, which is what a music record's `+4` holds
# directly.
MODE_NAMES = [
    "Off", "Room", "StudioA", "StudioB", "StudioC",
    "Hall", "SpaceEcho", "Echo", "Delay", "Pipe",
]


def find_module(blob):
    """Accept the IRX itself, or pull it out of an ISO9660 image."""
    if blob[:4] == b"\x7fELF":
        return blob
    return extract_from_iso(blob)


def extract_from_iso(iso):
    pvd = iso[16 * 2048:17 * 2048]
    if pvd[1:6] != b"CD001":
        raise SystemExit("not an IRX and not an ISO9660 image")
    root = pvd[156:190]
    lba = struct.unpack_from("<I", root, 2)[0]
    size = struct.unpack_from("<I", root, 10)[0]
    directory = iso[lba * 2048: lba * 2048 + size]
    offset = 0
    while offset < len(directory):
        length = directory[offset]
        if length == 0:
            offset = (offset // 2048 + 1) * 2048
            continue
        record = directory[offset:offset + length]
        name = record[33:33 + record[32]].decode("latin1")
        if name.upper().startswith("RSPU2DRV.IRX"):
            elba = struct.unpack_from("<I", record, 2)[0]
            esize = struct.unpack_from("<I", record, 10)[0]
            return iso[elba * 2048: elba * 2048 + esize]
        offset += length
    raise SystemExit("RSPU2DRV.IRX is not in the image's root directory")


def read_tables(module):
    def at(vaddr):
        return vaddr - DATA_FILE_TO_VADDR

    sizes = list(struct.unpack_from("<10I", module, at(SIZE_TABLE_VADDR)))
    presets = []
    for mode in range(PRESET_COUNT):
        base = at(PRESET_TABLE_VADDR + mode * PRESET_STRIDE)
        mask = struct.unpack_from("<I", module, base)[0]
        if mask != 0:
            raise SystemExit("mode %d has a non-zero field mask (%#x)" % (mode, mask))
        presets.append(struct.unpack_from("<32H", module, base + 4))
    return sizes, presets


def emit_header(sizes, presets):
    lines = []
    w = lines.append
    w("#pragma once")
    w("")
    w("// Generated by scripts/extract_spu2_reverb_presets.py -- do not hand-edit.")
    w("//")
    w("// The ten reverb presets out of the game's own IOP sound driver,")
    w("// RSPU2DRV.IRX, which is where a music record's `+4` reverb type is")
    w("// resolved. Field order and units are the driver's, read off its register")
    w("// writer at 0xF6F0:")
    w("//")
    w("//   * `sizeUnits` is the delay buffer, in eight-byte units. The driver")
    w("//     shifts it left by three for bytes and parks the buffer at the top of")
    w("//     sound RAM.")
    w("//   * every `*Size`, `*Src` and `*Dst` is an offset into that buffer, in")
    w("//     eight-byte units as well; the driver multiplies by four on the way to")
    w("//     the hardware register, because SPU2 addresses 16-bit words. Four")
    w("//     samples per unit, either way you count it.")
    w("//   * every `*Vol` and `inCoef*` is a signed Q15 coefficient.")
    w("")
    w("#include <array>")
    w("#include <cstddef>")
    w("#include <cstdint>")
    w("")
    w("namespace orphen::ported::sound")
    w("{")
    w("")
    w("  struct Spu2ReverbPreset")
    w("  {")
    w("    std::uint32_t sizeUnits;")
    for name, _reg, kind in REGISTERS:
        ctype = "std::uint16_t" if kind == "addr" else "std::int16_t"
        field = name.lower()
        parts = field.split("_")
        field = parts[0] + "".join(p.capitalize() for p in parts[1:])
        w("    %s %s;" % (ctype, field))
    w("  };")
    w("")
    w("  inline constexpr std::size_t kSpu2ReverbPresetCount = 10;")
    w("")
    w("  inline constexpr std::array<Spu2ReverbPreset, kSpu2ReverbPresetCount>")
    w("      kSpu2ReverbPresets{{")
    for mode in range(PRESET_COUNT):
        params = presets[mode]
        w("      // mode %d: %s" % (mode, MODE_NAMES[mode]))
        w("      {")
        w("          0x%04X," % sizes[mode])
        for index, (name, _reg, kind) in enumerate(REGISTERS):
            value = params[index]
            if kind == "coef":
                signed = value - 0x10000 if value >= 0x8000 else value
                w("          %d, // %s" % (signed, name))
            else:
                w("          0x%04X, // %s" % (value, name))
        w("      },")
    w("  }};")
    w("")
    w("} // namespace orphen::ported::sound")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("module", help="RSPU2DRV.IRX, or an ISO to pull it from")
    parser.add_argument("--header", help="write a C++ header here instead of a text dump")
    args = parser.parse_args()

    with open(args.module, "rb") as handle:
        module = find_module(handle.read())
    sizes, presets = read_tables(module)

    if args.header:
        with open(args.header, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(emit_header(sizes, presets))
        print("wrote " + args.header)
        return 0

    for mode in range(PRESET_COUNT):
        print("mode %d %s  buffer %#x bytes" % (mode, MODE_NAMES[mode], sizes[mode] * 8))
        for index, (name, reg, _kind) in enumerate(REGISTERS):
            print("    %-12s reg %#05x  %#06x" % (name, reg, presets[mode][index]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
